---
sickrage_install_dir: "{{ install_dir }}/sickrage"
sickrage_config_dir: "{{ install_dir }}/data/.sickrage"

sickrage_repo: https://github.com/SickRage/SickRage.git

# Backup Script
sickrage_backup_script_dir: "{{ install_dir }}/_backups/scritps"
sickrage_backup_command: tar -cpzf
sickrage_backup_filename: sickrage-`date \+%Y\%m\%d-%T`.tar.gz
sickrage_backup_sources: "*"
sickrage_backup_target: "{{ install_dir }}/_backups"
