---
- name: Check if installed
  stat: path=/apps/sickrage
  register: check_installed

- name: CentOS Install
  include: "centos.yml"
  when: ansible_distribution == 'CentOS' and check_installed.stat.exists == False